name: Generate ASCII Artwork

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repo
          uses: actions/checkout@v4
        
        - name: List Repo files
          run: ls -ltra


        - name: Execute Shell script
          run: |
            chmod +x ascii-script.sh 
            ./ascii-script.sh

        - name: Upload Dragon text file
          uses: actions/upload-artifact@v4
          with:
            name: dragon-text-file
            path: dragon-1.txt

    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps: 
        - name: Download dragon text file
          uses: actions/download-artifact@v5
          with:
            name: dragon-text-file
          
        - name: Test file exists
          run: grep -i "dragon" dragon-1.txt

    deploy_job:
        needs: [test_job]
        runs-on: ubuntu-latest
        steps:
        - name: Download dragon text file
          uses: actions/download-artifact@v5
          with:
            name: dragon-text-file
                        
        - name: Read File
          run: cat dragon-1.txt


